name: Inspect Contexts

on: [push]

jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          ls -la /home/runner/perflogs
          ls -la /home/runner
      
